sudo: required
services:
    - docker

before_install:
    - docker build -t jgutierrez91/reac-test-client -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jgutierrez91/reac-test-client  npm run test -- --coverage

after_success:
    - docker build -t jgutierrez91/multi-client  ./client
    - docker build -t jgutierrez91/multi-nginx  ./nginx
    - docker build -t jgutierrez91/multi-server  ./server
    - docker build -t jgutierrez91/multi-worker  ./worker
    #log into docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #pull the images to docker
    - docker push jgutierrez91/multi-client 
    - docker push jgutierrez91/multi-nginx 
    - docker push jgutierrez91/multi-server 
    - docker push jgutierrez91/multi-worker 
    
deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-481148435697
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    